#version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"

  app:
    build: .
    command: bash -c 'bash setup.sh && go run cmd/main.go'
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DRIVER=${DB_DRIVER}
      - DB_NAME=${DB_NAME}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_SCHEMA=${DB_SCHEMA}
    volumes:
      - .:/app
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
