#version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pgpassword123
      - POSTGRES_DB=balance-db
    ports:
      - "5432:5432"

  app:
    build: .
    command: bash -c 'bash setup.sh && go run cmd/main.go'
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=pgpassword123
      - DB_DRIVER=postgres
      - DB_NAME=balance-db
      - DB_HOST=db
      - DB_PORT=5432
      - DB_SCHEMA=public
      - DB_MAX_OPEN_CONNS=50
      - DB_MAX_IDLE_CONNS=25
      - DB_CONN_MAX_LIFE=120
      - PORT=7788
    volumes:
      - .:/app
    ports:
      - "7788:7788"
    depends_on:
      - db
